#!/usr/bin/env python3
"""Generate markdown variants of the site pages for `Accept: text/markdown`.

For every index.html in the repo a sibling index.md is written: YAML
frontmatter (title/description/image from meta tags), body content as
markdown, JSON-LD preserved in a fenced block — the same layout Cloudflare's
"Markdown for Agents" produces. Matching .htaccess files are regenerated so
agents negotiating text/markdown get Content-Type: text/markdown while
browsers keep receiving HTML.

If the live server already has a root .htaccess, save its content as
htaccess.base at the repo root: the generated root .htaccess will start with
it, followed by the Markdown for Agents block.

Token counts use the chars/4 estimate.

Usage: python3 generate_markdown.py [--check]
"""
import re
import sys
from html import unescape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin

ROOT = Path(__file__).resolve().parent
SITE = "https://gabriel.olynthe.org"
MARKER = "# Markdown for Agents (generated by generate_markdown.py)"

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "source", "track", "use", "wbr"}
SKIP_TAGS = {"script", "style", "noscript", "template", "svg", "button",
             "dialog", "form", "input", "label", "select", "option",
             "textarea", "nav", "footer", "iframe", "head", "title", "meta", "link"}
SKIP_CLASSES = {"skip", "theme-switch", "flag-wrap", "panel-backdrop"}
BLOCK_TAGS = {"p", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "figcaption", "hr", "li", "blockquote", "pre"}
CONTAINER_TAGS = {"div", "section", "aside", "main", "article", "header", "figure"}

ROOT_HTACCESS = MARKER + """
AddType 'text/markdown; charset=utf-8' .md

<IfModule mod_headers.c>
  Header merge Vary Accept
  <Files "index.md">
    Header set x-markdown-tokens "{md_tokens}"
    Header set x-original-tokens "{html_tokens}"
  </Files>
</IfModule>

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Directory requests (/, /en/, ...) -> index.md for markdown agents
  RewriteCond %{{HTTP:Accept}} text/markdown [NC]
  RewriteCond %{{REQUEST_FILENAME}}/index\\.md -f
  RewriteRule ^(.*?)/?$ $1/index.md [L]

  # Explicit /path/page.html -> /path/page.md for markdown agents
  RewriteCond %{{HTTP:Accept}} text/markdown [NC]
  RewriteCond %{{REQUEST_URI}} ^(.*)\\.html$
  RewriteCond %{{DOCUMENT_ROOT}}%1\\.md -f
  RewriteRule ^(.*)\\.html$ $1.md [L]
</IfModule>
"""

DIR_HTACCESS = """<IfModule mod_headers.c>
  <Files "index.md">
    Header set x-markdown-tokens "{md_tokens}"
    Header set x-original-tokens "{html_tokens}"
  </Files>
</IfModule>
"""


class Tree(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = ["#root", {}, []]
        self.stack = [self.root]

    def _node(self, tag, attrs):
        node = [tag, {k: (v or "") for k, v in attrs}, []]
        self.stack[-1][2].append(node)
        return node

    def handle_starttag(self, tag, attrs):
        node = self._node(tag, attrs)
        if tag not in VOID:
            self.stack.append(node)

    def handle_startendtag(self, tag, attrs):
        self._node(tag, attrs)

    def handle_endtag(self, tag):
        for i in range(len(self.stack) - 1, 0, -1):
            if self.stack[i][0] == tag:
                del self.stack[i:]
                return

    def handle_data(self, data):
        self.stack[-1][2].append([None, data])


def walk(node):
    for child in node[2]:
        yield child
        if child[0] is not None:
            yield from walk(child)


def find(node, tag):
    for child in walk(node):
        if child[0] == tag:
            return child
    return None


def skipped(node):
    tag, attrs = node[0], node[1]
    if tag is None:
        return False
    if tag in SKIP_TAGS:
        return True
    if attrs.get("aria-hidden") == "true" or "hidden" in attrs:
        return True
    if set(attrs.get("class", "").split()) & SKIP_CLASSES:
        return True
    return False


def squeeze(text):
    return re.sub(r"\s+", " ", text).strip()


def text_of(node):
    return squeeze("".join(child[1] for child in walk(node) if child[0] is None))


def inline(node, base):
    if node[0] is None:
        return re.sub(r"\s+", " ", node[1])
    tag, attrs, kids = node
    if skipped(node):
        return ""
    if tag == "br":
        return "\n"
    if tag == "img":
        alt, src = attrs.get("alt", "").strip(), attrs.get("src", "")
        return f"![{alt}]({urljoin(base, src)})" if alt and src else ""
    inner = "".join(inline(child, base) for child in kids)
    if tag == "a":
        href = attrs.get("href", "")
        return f"[{inner.strip()}]({urljoin(base, href)})" if href and inner.strip() else inner
    if tag in ("strong", "b") and inner.strip():
        return f"**{inner.strip()}**"
    if tag in ("em", "i") and inner.strip():
        return f"*{inner.strip()}*"
    if tag == "code" and inner.strip():
        return f"`{inner.strip()}`"
    return inner


def blocks(node, base):
    out, buf = [], []

    def flush():
        text = squeeze("".join(buf))
        buf.clear()
        if text:
            out.append(text)

    for child in node[2]:
        if child[0] is not None and skipped(child):
            continue
        if child[0] is not None and (child[0] in BLOCK_TAGS or child[0] in CONTAINER_TAGS):
            flush()
            out.extend(block(child, base))
        else:
            buf.append(inline(child, base))
    flush()
    return out


def list_block(node, base):
    out = []
    for li in node[2]:
        if li[0] != "li" or skipped(li):
            continue
        kids = [c for c in li[2] if not (c[0] is not None and skipped(c))]
        lead = ""
        if kids and kids[0][0] == "span" and set(kids[0][1].get("class", "").split()) & {"year", "tag"}:
            lead = squeeze("".join(inline(c, base) for c in kids[0][2]))
            lead = f"**{lead}:** " if lead else ""
            kids = kids[1:]
        lines = blocks(["#li", {}, kids], base)
        if "project" in li[1].get("class", "").split():
            lines = [f"**{re.sub(r'^#{1,6} ', '', l)}**" if l.startswith("#") else l
                     for l in lines]
        if lead and lines:
            lines[0] = lead + lines[0]
        elif lead:
            lines = [lead]
        if lines:
            out.append("\n".join([f"- {lines[0]}"] + [f"  {l}" for l in lines[1:]]))
    return ["\n".join(out)] if out else []


def block(node, base):
    tag, attrs, kids = node
    if tag is None or skipped(node):
        return []
    if re.fullmatch(r"h[1-6]", tag):
        label = attrs.get("aria-label", "").strip()
        text = label or squeeze("".join(inline(c, base) for c in kids))
        return [f"{'#' * int(tag[1])} {text}"] if text else []
    if tag in ("ul", "ol"):
        return list_block(node, base)
    if tag == "hr":
        return ["---"]
    if tag in CONTAINER_TAGS or tag not in BLOCK_TAGS:
        return blocks(node, base)
    text = squeeze("".join(inline(c, base) for c in kids))
    if not text:
        return []
    if tag == "figcaption":
        return [f"*{text}*"]
    return [text]


def convert(html_text, base):
    parser = Tree()
    parser.feed(html_text)
    head, body = find(parser.root, "head"), find(parser.root, "body")

    meta = {}
    for child in walk(head):
        if child[0] == "meta":
            key = child[1].get("name") or child[1].get("property")
            if key and child[1].get("content"):
                meta.setdefault(key, child[1]["content"])

    front = []
    if meta.get("title") or meta.get("og:title"):
        front.append(f"title: {yaml(meta.get('title') or meta.get('og:title'))}")
    if meta.get("description") or meta.get("og:description"):
        front.append(f"description: {yaml(meta.get('description') or meta.get('og:description'))}")
    if meta.get("og:image"):
        front.append(f"image: {meta['og:image']}")

    jsonld = []
    for child in walk(parser.root):
        if child[0] == "script" and "application/ld+json" in child[1].get("type", ""):
            raw = "".join(c[1] for c in child[2] if c[0] is None).strip()
            if raw:
                jsonld.append(unescape(raw))

    parts = []
    if front:
        parts.append("---\n" + "\n".join(front) + "\n---")
    parts.append("\n\n".join(blocks(body, base)))
    if jsonld:
        parts.append("```json\n" + "\n".join(jsonld) + "\n```")
    return "\n\n".join(p for p in parts if p.strip()) + "\n"


def yaml(value):
    if re.search(r'[:#]|^\s|\s$', value):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def index_html_pages():
    pages = [ROOT / "index.html"]
    pages += sorted(p for p in ROOT.glob("*/index.html") if p.is_file())
    return pages


def write(path, content, check=False):
    if check:
        current = path.read_text("utf-8") if path.exists() else ""
        if current != content:
            print(f"outdated: {path.relative_to(ROOT)}")
            return False
        print(f"ok: {path.relative_to(ROOT)}")
        return True
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({len(content)} bytes)")
    return True


def main():
    check = "--check" in sys.argv[1:]
    all_ok = True
    server_base_path = ROOT / "htaccess.base"
    server_base = ""
    if server_base_path.exists():
        server_base = server_base_path.read_text("utf-8").rstrip() + "\n\n"
    for page in index_html_pages():
        html_text = page.read_text("utf-8")
        rel_dir = page.parent.relative_to(ROOT).as_posix()
        base = SITE if rel_dir == "." else f"{SITE}/{rel_dir}"
        md = convert(html_text, base)
        md_tokens, html_tokens = len(md) // 4, len(html_text) // 4
        all_ok &= write(page.with_name("index.md"), md, check)
        data = DIR_HTACCESS.format(md_tokens=md_tokens, html_tokens=html_tokens)
        if rel_dir == ".":
            data = server_base + ROOT_HTACCESS.format(md_tokens=md_tokens, html_tokens=html_tokens)
        else:
            target = page.parent / ".htaccess"
            if target.exists():
                current = target.read_text("utf-8")
                data = re.sub(r'Header set x-markdown-tokens "\d+"',
                              f'Header set x-markdown-tokens "{md_tokens}"', current)
                data = re.sub(r'Header set x-original-tokens "\d+"',
                              f'Header set x-original-tokens "{html_tokens}"', data)
        all_ok &= write(page.parent / ".htaccess", data, check)
    if check and not all_ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
